version: '3.8'

services:
  middleware:
    build: 
      context: ./middleware
      dockerfile: python.Dockerfile
      shm_size: 12gb
    shm_size: 12gb
    restart: always
    container_name:  middleware
    privileged: true
    user: root
    volumes:
      - ./middleware:/middleware
      - ./../.cache/huggingface/hub:/root/.cache/huggingface/hub
    entrypoint: 'watchmedo auto-restart --directory=/middleware --pattern="*.py,*.js,*.html" --recursive python app.py'
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    ports:
      - '80:80'
networks:
  docker_network:
    driver: bridge
